package com.revature.project0;

import java.io.*;
import java.sql.*;
import java.util.*;
import java.math.*;

 /**
  * Join Value Object.
  * This class is value object representing database table join
  * This class is intented to be used together with associated Dao object.
  */

 /**
  * This sourcecode has been generated by FREE DaoGen generator version 2.4.1.
  * The usage of generated code is restricted to OpenSource software projects
  * only. DaoGen is available in http://titaniclinux.net/daogen/
  * It has been programmed by Tuomo Lukka, Tuomo.Lukka@iki.fi
  *
  * DaoGen license: The following DaoGen generated source code is licensed
  * under the terms of GNU GPL license. The full text for license is available
  * in GNU project's pages: http://www.gnu.org/copyleft/gpl.html
  *
  * If you wish to use the DaoGen generator to produce code for closed-source
  * commercial applications, you must pay the lisence fee. The price is
  * 5 USD or 5 Eur for each database table, you are generating code for.
  * (That includes unlimited amount of iterations with all supported languages
  * for each database table you are paying for.) Send mail to
  * "Tuomo.Lukka@iki.fi" for more information. Thank you!
  */



public class Join implements Cloneable, Serializable {

    /** 
     * Persistent Instance variables. This data is directly 
     * mapped to the columns of database table.
     */
    private int userID;
    private int fromAcct;
    private int toAcct;
    private String Timestamp;
    private String stat;



    /** 
     * Constructors. DaoGen generates two constructors by default.
     * The first one takes no arguments and provides the most simple
     * way to create object instance. The another one takes one
     * argument, which is the primary key of the corresponding table.
     */

    public Join () {

    }

    public Join (int userIDIn) {

          this.userID = userIDIn;

    }


    /** 
     * Get- and Set-methods for persistent variables. The default
     * behaviour does not make any checks against malformed data,
     * so these might require some manual additions.
     */

    public int getUserID() {
          return this.userID;
    }
    public void setUserID(int userIDIn) {
          this.userID = userIDIn;
    }

    public int getFromAcct() {
          return this.fromAcct;
    }
    public void setFromAcct(int fromAcctIn) {
          this.fromAcct = fromAcctIn;
    }

    public int getToAcct() {
          return this.toAcct;
    }
    public void setToAcct(int toAcctIn) {
          this.toAcct = toAcctIn;
    }

    public String getTimestamp() {
          return this.Timestamp;
    }
    public void setTimestamp(String TimestampIn) {
          this.Timestamp = TimestampIn;
    }

    public String getStat() {
          return this.stat;
    }
    public void setStat(String statIn) {
          this.stat = statIn;
    }



    /** 
     * setAll allows to set all persistent variables in one method call.
     * This is useful, when all data is available and it is needed to 
     * set the initial state of this object. Note that this method will
     * directly modify instance variales, without going trough the 
     * individual set-methods.
     */

    public void setAll(int userIDIn,
          int fromAcctIn,
          int toAcctIn,
          String TimestampIn,
          String statIn) {
          this.userID = userIDIn;
          this.fromAcct = fromAcctIn;
          this.toAcct = toAcctIn;
          this.Timestamp = TimestampIn;
          this.stat = statIn;
    }


    /** 
     * hasEqualMapping-method will compare two Join instances
     * and return true if they contain same values in all persistent instance 
     * variables. If hasEqualMapping returns true, it does not mean the objects
     * are the same instance. However it does mean that in that moment, they 
     * are mapped to the same row in database.
     */
    public boolean hasEqualMapping(Join valueObject) {

          if (valueObject.getUserID() != this.userID) {
                    return(false);
          }
          if (valueObject.getFromAcct() != this.fromAcct) {
                    return(false);
          }
          if (valueObject.getToAcct() != this.toAcct) {
                    return(false);
          }
          if (this.Timestamp == null) {
                    if (valueObject.getTimestamp() != null)
                           return(false);
          } else if (!this.Timestamp.equals(valueObject.getTimestamp())) {
                    return(false);
          }
          if (this.stat == null) {
                    if (valueObject.getStat() != null)
                           return(false);
          } else if (!this.stat.equals(valueObject.getStat())) {
                    return(false);
          }

          return true;
    }



    /**
     * toString will return String object representing the state of this 
     * valueObject. This is useful during application development, and 
     * possibly when application is writing object states in textlog.
     */
    public String toString() {
        StringBuffer out = new StringBuffer(this.getDaogenVersion());
        out.append("\nclass Join, mapping to table join\n");
        out.append("Persistent attributes: \n"); 
        out.append("userID = " + this.userID + "\n"); 
        out.append("fromAcct = " + this.fromAcct + "\n"); 
        out.append("toAcct = " + this.toAcct + "\n"); 
        out.append("Timestamp = " + this.Timestamp + "\n"); 
        out.append("stat = " + this.stat + "\n"); 
        return out.toString();
    }


    /**
     * Clone will return identical deep copy of this valueObject.
     * Note, that this method is different than the clone() which
     * is defined in java.lang.Object. Here, the retuned cloned object
     * will also have all its attributes cloned.
     */
    public Object clone() {
        Join cloned = new Join();

        cloned.setUserID(this.userID); 
        cloned.setFromAcct(this.fromAcct); 
        cloned.setToAcct(this.toAcct); 
        if (this.Timestamp != null)
             cloned.setTimestamp(new String(this.Timestamp)); 
        if (this.stat != null)
             cloned.setStat(new String(this.stat)); 
        return cloned;
    }



    /** 
     * getDaogenVersion will return information about
     * generator which created these sources.
     */
    public String getDaogenVersion() {
        return "DaoGen version 2.4.1";
    }

}

